### PR TITLE
fix: cache ignored glob by directory 

### PR DESCRIPTION
**Pull request by aminya**
This fixes a bug in the previous release.

### CODE REVIEW

**Comment by UziTech** [comment]
It would be great if there were tests that could have caught this bug before the last release or before the next time this bug pops up. 😁

**Comment by aminya** [comment]
> It would be great if there were tests that could have caught this bug before the last release or before the next time this bug pops up. 😁

Yeah. We should add more tests to the project. 

I am still experimenting with chokidar. It is convenient, but not necessarily the fastest. Not sure if it is the best solution for making the path cache. 

https://github.com/atom/node-pathwatcher

**Comment by aminya** [comment]
One optimization to perform is to maybe give up tracking the changes if the number of files is larger than some amount

**Comment by aminya** [comment]
Another solution is to add event listeners to Atom's file/folder adding/removing. So, only if the user adds/remove a file/folder inside Atom itself (using TreeView for example), then we should track that.

**Comment by aminya** [comment]
We could also use fb-watchman, which is a native package. I think it has a better performance compared to chokidar and atom/pathwatcher

**Pull request merged**
