### PR TITLE
PathsCache with `find`

### PR DESCRIPTION
**Pull request by avaly**
This PR introduces a better cache building approach for systems which have `find` available (e.g. Mac OS, *nix).

This new cache code does remove the watching feature. However a more performant watch is being introduced in Atom 1.21: https://github.com/atom/atom/pull/14853 and we can use this to bind one single watcher for the whole project

Comparison cache build on a project with 7000+ files spread out in hundreds of folders:

- before: `31.682s`
- after: `2.274s`

### CODE REVIEW

**Comment by saschagehlich** [comment]
Thank you very much for your contribution @avaly! This looks good, but I'd like to keep the watching feature for macOS and *nix systems, so I'd like to wait for 1.21 to be released and switch to the new watching feature before releasing this.

**Comment by avaly** [comment]
@saschagehlich Sure, I understand. I'll try to integrate the new watcher once 1.21 is out of beta. Otherwise, feel free to use this PR as a starter if you plan on doing that earlier.

**Comment by avaly** [comment]
@saschagehlich I've updated this PR with the new project watcher support.

**Comment by saschagehlich** [comment]
Thanks a lot @avaly!

**Pull request merged**
