### PR TITLE
WIP: v2

### PR DESCRIPTION
**Pull request by saschagehlich**
I rewrote the module so that it caches all file paths in all open projects and suggests the paths whenever the current line is matching a specific regex. For this, I introduced a `scopes` option that the user can use to specify their own behavior. See the `README.md` for an example.

Things that are missing:
- [x] Proper multi-project handling
- [x] Specs
- [x] Sort by distance from current file

### CODE REVIEW

**Comment by joefitzgerald** [comment]
:tada: yay for ES6. You might want to add .eslintrc in the root and the specs directory (and use linter + linter-eslint); it'll let you do away with some of the directives you have for globals. See https://github.com/joefitzgerald/autocomplete-go for an example. 

I also separated out the config from main, but that's not essential. 

Great to see you working on this PR. Welcome back!

**Comment by saschagehlich** [comment]
I'd rather use the `standard` linter as I use it in all my other ES6 projects. What do you think?

**Comment by saschagehlich** [comment]
Oh and BTW @joefitzgerald, I also separated out the config since it was too messy to stay in the main code ;)

**Comment by joefitzgerald** [comment]
> I'd rather use the standard linter as I use it in all my other ES6 projects. What do you think?

:+1:

**Comment by saschagehlich** [comment]
@joefitzgerald Specs are green - I guess we need a couple more scopes. Any ideas? I'd suggest `python`, `ruby`, `lua`, `c/c++/c#`. Anything else?

**Comment by joefitzgerald** [comment]
:+1:. The only additional thing I'd think about is how you might update the cache (or invalidate it in response to filesysytem changes (the extreme example being the use of fs-notify or equivalent).

**Comment by saschagehlich** [comment]
@joefitzgerald Right now I have the "Rebuild Cache" command that you can trigger. But yeah, it should happen automatically. I'll look into that.

**Comment by saschagehlich** [comment]
@joefitzgerald How about https://atom.io/docs/api/v1.5.3/GitRepository#instance-onDidChangeStatuses ?

**Comment by saschagehlich** [comment]
@joefitzgerald Should be ready to merge! :) :tada:

**Comment by saschagehlich** [comment]
Used it for a while now - needs some performance tweaks for cache rebuilding on file system updates. Right now it rebuilds the whole cache, taking about 3 seconds for my current project.

**Comment by joefitzgerald** [comment]
> needs some performance tweaks for cache rebuilding on file system update

So wait until that's done?

**Comment by saschagehlich** [comment]
Yeah, i'll take a look at it soon

**Comment by saschagehlich** [comment]
Another bug: When multiple panes are open, it rebuilds the cache multiple times, slowing things down even more.

**Comment by Stanzilla** [comment]
@saschagehlich are you still working on this? I feel like caching might help with the freezing problem lots of people are having.

**Comment by joefitzgerald** [comment]
Closing as abandoned.

**Pull request closed without merging**
