### PR TITLE
Use native fuzzaldrin plus fast

### PR DESCRIPTION
**Pull request by aminya**
This replaces fuzzaldrin plus with fuzzaldrin plus fast which is a native module that uses C++ bindings to perform fast fuzzy-search.

### CODE REVIEW

**Comment by aminya** [comment]
@atom-community Could someone review this?

**Comment by aminya** [comment]
Do you have access to this repo? How can I become a member? Who is the owner?

@uzitech @smashwilson

**Comment by UziTech** [comment]
I only have permission for sync-settings. I asked a while ago which owners were still active with no response. @atom-community/owners if someone could give me access I wouldn't mind helping maintain more repos in @atom-community

**Comment by UziTech** [comment]
Since fuzzaldrin-plus-fast uses node-gyp this is going to cause the user to rebuild the package on new versions of Atom that update electron. I'm not entirely convinced that is worth a little speed improvement.

Is there a benchmark showing a significant improvement?

**Comment by aminya** [comment]
> Since fuzzaldrin-plus-fast uses node-gyp this is going to cause the user to rebuild the package on new versions of Atom that update electron. I'm not entirely convinced that is worth a little speed improvement.
> 
> Is there a benchmark showing a significant improvement?

`fuzzaldrin-plus-fast` ships prebuilt binaries using `napi` which is forward compatible. They will not need to rebuild.

**Pull request merged**
