### PR TITLE
Change provider to take minimumWordLength into account

### PR DESCRIPTION
**Pull request by MoritzKn**

### CODE REVIEW

**Comment by leggsimon** [comment]
Cool, I've recently been added as a collaborator on this repo and trying to inject some life back into it. My first task though is to figure out why all the builds/test suite fail.

Please bear with me and if you know how to fix the test suite locally it'd be great if you could point me in the right direction.

**Comment by MoritzKn** [comment]
@leggsimon I've also noted that. I will try to take a look over it maybe I can help you out.

**Comment by MoritzKn** [comment]
@leggsimon take a look at #102

**Comment by leggsimon** [comment]
So a rebase should fix this build now

**Pull request merged**
